#!/usr/bin/env bash
# Creates file containing own pid and change default response actions of signals
sudo touch /var/run/holbertonscript.pid
sudo chmod 666 /var/run/holbertonscript.pid
echo $$ >> /var/run/holbertonscript.pid

function handler_sigterm()
{
    echo I hate the kill command
    rm /var/run/holbertonscript.pid
}
function handler_sigquit()
{
    echo echo Y U no love me?!
    rm /var/run/holbertonscript.pid
}

trap handler_sigterm SIGTERM
trap "echo Y U no love me?!" SIGINT
trap handler_sigquit SIGQUIT

while ((1))
do
    echo "To infinity and beyond"
    sleep 2
done

