#!/usr/bin/env bash
# Displays Best School 10 times with other words in lines 3, 7
I=0
while [ $I -lt 10 ]
do
    if [ $I -eq 3 ]
    then
        echo "bad luck"
    elif [ $I -eq 7 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    let I++
done
