#!/usr/bin/env bash
# Check if school file exist, is empty or it's a regular file
file="holbertonschool"
if [ -e $file ]
then
    echo "school file exists"
    if [ -s $file ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f $file ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi

